Repository appleseedlab/maki, pull requests merged in 2024-07, with the labels that each got.

#61 IsICERepresentableByInt16
  lib/MakiASTConsumer.cc
  test/Tests/ice_bits.c
Labels: enhancement

#66 Optimize finding aligned AST nodes to match on single AST pass
  lib/AlignmentMatchers.cc
Labels: optimization

#63 Fix property checks for paren exprs
  lib/MakiASTConsumer.cc
  test/Tests/addressed_arguments.c
  test/Tests/addressed_invocation.c
Labels: bug-fix
